Fix running some algorithms on Python 3
The itertools.izip() function is replaced by the built-in function zip()
in Python 3. To support both Python 2 and Python 3, use a compatibility
library for this function. This fixes the following error:

    AttributeError: module 'itertools' has no attribute 'izip'